plugins {
    id 'com.android.library'
}

android {
    namespace 'org.nova.mnn'
    compileSdk 35

    defaultConfig {
        minSdk 24
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
